version: 2.1

commands:
  prepare_for_test:
    description: "Prepare for test."
    steps:
      - restore_cache:
          keys:
            - v1-gtest-cache-{{ .Branch }}-{{ .Revision }}-{ checksum ".circleci/build_googletest.sh" }}
            - v1-gtest-cache-{{ .Branch }}-{{ .Revision }}-
            - v1-gtest-cache-{{ .Branch }}-
      - run:
          name: download and build google test
          command: |
            if [ ! -d tests/googletest ]; then
              bash .circleci/build_googletest.sh;
            fi
      - save_cache:
          key: v1-gtest-cache-{{ .Branch }}-{{ .Revision }}-{{ checksum ".circleci/build_googletest.sh" }}
          paths:
            - tests/googletest
  prepare_for_cmake:
    description: "Prepare directory for cmake."
    steps:
      - run:
          name: prepare build directory
          command: |
            mkdir build && cd build
jobs:
  google_test:
    working_directory: ~/test
    docker:
      - image: rhikimochi/opencv-docker:v0.14
    steps:
      - checkout
      - prepare_for_test
      - prepare_for_cmake
      - run:
          name: build unit test
          command: |
            cmake .. -DGTEST=ON -DTEST_LEVEL=unit && make
      - run:
          name: build integration test
          command: |
            cmake .. -DGTEST=ON -DTEST_LEVEL=integration && make
      - run:
          name: build system test
          command: |
            cmake .. -DGTEST=ON -DTEST_LEVEL=system && make
      - run:
          name: back to working directory
          command: cd ..
      - run:
          name: execute unit test
          command: ./gazosan_unit_test
      - run:
          name: execute integration test
          command: ./gazosan_integration_test
      - run:
          name: execute syetem test
          command: ./gazosan_system_test
  build_library:
    working_directory: /tmp/build
    docker:
      - image: rhikimochi/opencv-docker:v0.14
    steps:
      - checkout
      - prepare_for_cmake
      - run:
          name: build gazosan
          command: cmake .. -DGTEST=OFF && make && cd ..
      - run:
          name: move static library
          command: mv build/libimageDiffCalc.a libimageDiffCalc.a
      - persist_to_workspace:
          root: /tmp/build
          paths:
            - libimageDiffCalc.a
  build_and_deploy_image:
    working_directory: ~/build
    machine: true
    environment:
      DOCKER_HUB_REPO: gazo-san
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Move library
          command: mv /tmp/build/libimageDiffCalc.a ~/build/
      - run:
          name: Build and tagged image
          command: |
            docker build -t "$DOCKER_HUB_USER"/"$DOCKER_HUB_REPO":"${CIRCLE_TAG/v/}" .
            docker tag "$DOCKER_HUB_USER"/"$DOCKER_HUB_REPO":"${CIRCLE_TAG/v/}" "$DOCKER_HUB_USER"/"$DOCKER_HUB_REPO":latest
      - run:
          name: Login docker hub
          command: docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_TOKEN"
      - run:
          name: Push image
          command: |
            docker push "$DOCKER_HUB_USER"/"$DOCKER_HUB_REPO":"${CIRCLE_TAG/v/}"
            docker push "$DOCKER_HUB_USER"/"$DOCKER_HUB_REPO":latest
      - run:
          name: Logout docker
          command: docker logout
  deploy_library:
    working_directory: ~/deploy
    docker:
      - image: circleci/node:stretch
    environment:
      OWNER: lifull-dev
      REPO: Gazo-san
      UPLOAD_FILE: /tmp/build/libimageDiffCalc.a
    steps:
      - attach_workspace:
          at: /tmp/build
      - run:
          name: Store upload url and upload assets
          command: |
            UPLOAD_URL_RAW=$(curl -X GET -H "Authorization: token $GITHUB_TOKEN" \
                 "https://api.github.com/repos/$OWNER/$REPO/releases/tags/$CIRCLE_TAG" \
                 | jq '.upload_url')
            UPLOAD_URL=$(echo ${UPLOAD_URL_RAW%\{*} | tr -d \")
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Content-Type: $(file -b --mime-type $UPLOAD_FILE)" \
                 --data-binary @$UPLOAD_FILE \
                 "$UPLOAD_URL?name=$(basename $UPLOAD_FILE)"
workflows:
  version: 2
  test:
    jobs:
      - google_test
  build-deploy:
    jobs:
      - build_library:
          filters: &filters
            tags:
              only: /^v[0-9]{1,}(\.[0-9]{1,}){2}$/
            branches:
              ignore: /.*/
      - deploy_library:
          requires:
            - build_library
          filters: *filters
      - build_and_deploy_image:
          requires:
            - build_library
          filters: *filters
